In [ ]:
import datetime as dt
import pandas as pd

In [ ]:
startstr = '221228'
startdate = dt.datetime.strptime(startstr, '%y%m%d').date()
startdate

datetime.date(2022, 12, 28)

In [ ]:
def get_bridge(date):
    if (
        date.month != (date + dt.timedelta(days=2)).month
        ) or (
        date.month != (date - dt.timedelta(days=1)).month):
        return 1
    else:
        return 0

In [ ]:
records = []
thisdate = startdate

while True:
    ready = 0
    bridge = get_bridge(thisdate)
    records.append((thisdate.strftime('%y%m%d'), bridge, ready))
    thisdate = (thisdate - dt.timedelta(days=2))
    if thisdate.year < 1990:
        break

In [ ]:
recordsdf = pd.DataFrame.from_records(records, columns=['datelabel', 'bridgemonth', 'era5ready', ])
recordsdf['erapreproc'] = 0
recordsdf['wpsready'] = 0
recordsdf['wrfstarted'] = '' 
recordsdf['wrfcomplete'] = '' 
recordsdf['wrfsuccessful'] = 0
recordsdf['dataarchived'] = 0
recordsdf['wrfcleanup'] = 0
recordsdf['wpscleanup'] = 0
recordsdf['era5cleanp'] = 0
recordsdf

,datelabel,bridgemonth,era5ready,erapreproc,wpsready,wrfstarted,wrfcomplete,wrfsuccessful,dataarchived,wrfcleanup,wpscleanup,era5cleanp
0,221228,0,0,0,0,,,0,0,0,0,0
1,221226,0,0,0,0,,,0,0,0,0,0
2,221224,0,0,0,0,,,0,0,0,0,0
3,221222,0,0,0,0,,,0,0,0,0,0
4,221220,0,0,0,0,,,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
6020,900110,0,0,0,0,,,0,0,0,0,0
6021,900108,0,0,0,0,,,0,0,0,0,0
6022,900106,0,0,0,0,,,0,0,0,0,0
6023,900104,0,0,0,0,,,0,0,0,0,0
6024,900102,0,0,0,0,,,0,0,0,0,0

In [ ]:
recordsdf.to_feather('status.feather')